apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prefect-server.fullname" . }}-hasura
  labels: 
    {{- include "hasura.labels" . | nindent 6 }}
  {{- if ( include "hasura.annotations" . ) }}
  annotations:
    {{- ( include "hasura.annotations" . ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.hasura.replicaCount }}
  selector:
    matchLabels:
      {{- include "hasura.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hasura.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.hasura.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "prefect-server.serviceAccountName" . }}
      {{- with .Values.hasura.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hasura
          {{- with .Values.hasura.securityContext -}}          
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.hasura.image.repository }}:{{ .Values.hasura.image.version }}"
          imagePullPolicy: {{ .Values.hasura.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.global.hasura.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          {{- with .Values.hasura.resources -}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.hasura.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.hasura.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.hasura.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
