apiVersion: v1
kind: Service
metadata:
  name: {{ include "prefect-server.fullname" . }}-hasura
  labels: 
    {{- include "hasura.labels" . | nindent 4 }}
  {{- if ( include "hasura.annotations" . ) }}
  annotations:
    {{- ( include "hasura.annotations" . ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.hasura.service.type }}
  ports:
    - port: {{ .Values.global.hasura.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hasura.selectorLabels" . | nindent 4 }}
