# prefect-server configuration

# image provides configuration for all prefect images
# this notably excludes the hasura image
image:
  version: "latest"
  pullPolicy: IfNotPresent

# imagePullSecrets provides configuration to reference the k8s Secret
# resources the Helm chart's pods can get credentials from to pull
# their images.
imagePullSecrets: []

# labels to merge into all object configurations
labels: {}

# matchLabels defines extra selection labels to merge into all
# object configurations
matchLabels: {}

# annotations to merge into all object configurations
# NOTE: These will not apply to the postgresql subchart
# and must be defined within `postgresql` as well if that
# is desired
annotations: null

# fqdnSuffix determines the string appended to names when
# determining the fully qualified domain name of services for
# internal communication
fqdnSuffix: "svc.cluster.local"

# postgresql configures the backing database
# NOTE: the variables names must remain as is to match the
# bitnami subchart even if the bitnami subchart is not being
# used, these variables are used to create the connection
# string
postgresql:
  postgresqlDatabase: prefect
  postgresqlUsername: prefect

  # existingSecret configures which secret should be referenced
  # for access to the database. If null and `useSubChart` is
  # enabled, the secret will be generated. If using an external
  # postgres service, this value should be set to a secret
  # containing the key `postgresql-password`
  existingSecret: null

  # postgresqlPassword sets the password to be used if
  # `existingSecret` is not set. This is the password for
  # `postgresqlUsername` and will be set within the secret at
  # the key `postgresql-password`
  # postgresqlPassword: use-a-strong-password

  # servicePort configures the port that the database should be
  # accessed at
  servicePort: 5432

  # externalHostname defines the address to contact an externally
  # managed postgres database instance at. This is not required if
  # `internalPostgres` is `true`
  externalHostname: ""

  # useSubChart determines if a this chart should deploy a
  # user-manager postgres database or use an externally managed
  # postgres instance. If `useSubChart` is `true`, the
  # bitnami/postgresql subchart will be deployed
  useSubChart: true

  # postgresql configuration below here is only used if using
  # the subchart

  # persistence enables a PVC that stores the database between
  # deployments. If making changes to the database deployment, this
  # PVC will need to be deleted for database changes to take effect.
  # This is especially notable when the authentication password
  # changes on redeploys.
  # This is disabled by default because we do not recommend using
  # the subchart deployment for production deployments.
  persistence:
    enabled: false
    size: 8Gi

  initdbUser: postgres

  initdbScripts:
    create_pgcrypto.sql: |
      -- create pgcrypto extension, required for Hasura UUID
      CREATE EXTENSION IF NOT EXISTS pgcrypto;
      CREATE EXTENSION IF NOT EXISTS "pg_trgm";
      SET TIME ZONE 'UTC';

# prefectConfig allows override of prefect_server/config.toml values
# Values placed here will result in environment variable definitions
# starting with "PREFECT_SERVER__" and will be passed to TODO
prefectConfig:
  env: "local"
  debug: "false"
  queued_runs_returned_limit: "25"
  hasura:
    execute_retry_seconds: "10"
  logging:
    level: "DEBUG"
    format: "[%(asctime)s] %(levelname)s - %(name)s | %(message)s"
  services:
    scheduler:
      scheduler_loop_seconds: "300"
    lazarus:
      resurrection_attempt_limit: "3"
  telemetry:
    enabled: "true"


# hasura configures the Prefect hasura deployment and service
# which creates a graphql api from the postgres database
hasura:
  port: 3000

  # hasura.image configures the docker image used for hasura
  # and is the only image in the chart that is not hosted by
  # Prefect
  image:
    name: hasura/graphql-engine
    tag: v1.3.0
    pullPolicy: null
    pullSecrets: []

  options:
    queryPlanCacheSize: "100"

  service:
    # type defines the service type and defaults to ClusterIP
    # because this service does not need to be exposed outside
    # the cluster
    type: ClusterIP

  labels: {}
  annotations: []
  replicaCount: 1
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}


# graphql configures the Prefect graphql deployment and service
# which provides a python graphql server on starlette
graphql:
  port: 4201

  # containerPort is currently hardcoded in the container and
  # should not be changed (?)
  containerPort: 3000

  image:
    repository: prefecthq/server
    version: null
    pullPolicy: null
    pullSecrets: []

  service:
    type: ClusterIP

  labels: {}
  annotations: null
  replicaCount: 1
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  init:
    resources: {}

# apollo configures the Prefect apollo deployment and service
# which provides a unified graphql schema for users and the UI
# to interact with
apollo:
  port: 4200
  image:
    repository: prefecthq/apollo
    version: null
    pullPolicy: null
    pullSecrets: []
  options:
    telemetryEnabled: true

  service:
    # type defines the service type and defaults to LoadBalancer
    # to expose the apollo service to users and the UI.
    type: LoadBalancer
    # port allows specification of a service port different than
    # the value at apollo.port
    port: null

  labels: {}
  annotations: null
  replicaCount: 1
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

# ui configures the Prefect ui deployment and service
ui:
  port: 8080
  image:
    repository: prefecthq/ui
    version: null
    pullPolicy: null
    pullSecrets: []

  # apolloApiUrl defines the default gateway to the Apollo
  # GraphQL server. This location must be accessible by the
  # user of the API because the browser is making requests
  # (not the ui server)
  apolloApiUrl: http://localhost:4200/graphql

  service:
    # type defines the service type and defaults to LoadBalancer
    # to expose the ui service to users and the UI.
    type: LoadBalancer
    # port allows specification of a service port different than
    # the value at ui.port
    port: null

  labels: {}
  annotations: null
  replicaCount: 1
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

# towel configures the Prefect towel deployment which provides
# a group of useful services
towel:
  image:
    repository: prefecthq/server
    version: null
    pullPolicy: null
    pullSecrets: []

  service:
    type: ClusterIP

  labels: {}
  annotations: null
  replicaCount: 1
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

serviceAccount:
  # create specifies whether a service account should be created to manage
  # the prefect-server infrastructure
  create: true

  # name sets the name of the service account to use
  # If not set and create is true, a name is generated using the
  # prefect-server.nameField template
  name: null

