apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prefect-server.nameField" . }}
  labels: 
    {{- include "prefect-server.commonLabels" . | nindent 4 }}
  {{- include "prefect-server.annotations" . | nindent 2 }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      {{- include "prefect-server.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prefect-server.matchLabels" . | nindent 8 }}
    spec:
      {{- include "prefect-server.imagePullSecrets" . | nindent 6 -}}
      serviceAccountName: {{ include "prefect-server.serviceAccountName" . }}
      {{- with .Values.ui.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ui
          {{- with .Values.ui.securityContext -}}          
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.ui.image.name }}:{{ .Values.ui.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy | default .Values.image.pullPolicy }}
          command: 
            - "/intercept.sh"
          env:
            - name: PREFECT_SERVER__APOLLO_URL
              value: {{ .Values.ui.apolloApiUrl }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          {{- with .Values.ui.resources -}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
