apiVersion: v1
kind: Service
metadata:
  name: {{ include "prefect-server.fullname" . }}-ui
  labels: 
    {{- include "ui.labels" . | nindent 4 }}
  {{- if ( include "ui.annotations" . ) }}
  annotations:
    {{- ( include "ui.annotations" . ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.global.ui.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ui.selectorLabels" . | nindent 4 }}
