apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prefect-server.nameField" . }}
  labels: 
    {{- include "prefect-server.commonLabels" . | nindent 4 }}
  {{- include "prefect-server.annotations" . | nindent 2 -}}
spec:
  replicas: {{ .Values.apollo.replicaCount }}
  selector:
    matchLabels:
      {{- include "prefect-server.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prefect-server.matchLabels" . | nindent 8 }}
    spec:
      {{- include "prefect-server.imagePullSecrets" . | nindent 6 -}}
      serviceAccountName: {{ include "prefect-server.serviceAccountName" . }}
      {{- with .Values.apollo.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: apollo
          {{- with .Values.apollo.securityContext -}}          
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.apollo.image.name }}:{{ .Values.apollo.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.apollo.image.pullPolicy | default .Values.image.pullPolicy }}
          command:
            - bash
            - "-c"
            - "/apollo/post-start.sh && npm run serve"
          env:
            - name: HASURA_API_URL
              value: {{ include "prefect-server.hasura-api-url" . }}
            - name: PREFECT_API_URL
              value: {{ include "prefect-server.graphql-api-url" . }}
            - name: PREFECT_API_HEALTH_URL
              value: {{ include "prefect-server.graphql-health-url" . }}
            - name: GRAPHQL_SERVICE_HOST
              value: "http://{{ include "prefect-server.graphql-hostname" . }}"
            - name: GRAPHQL_SERVICE_PORT
              value: {{ .Values.graphql.port | quote }}
            {{- (include "prefect-server.envConfig" .) | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.apollo.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: http
          readinessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: http
          {{- with .Values.apollo.resources -}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.apollo.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.apollo.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.apollo.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
