config:

  # Cloud provider specific configuration ------------------------------------------------------------------------------

  # Choose a provider to use, one of azure, gcloud, aws
  prefect-server:provider: gcp

  # Azure ----------------------------------------------------------

  azure:environment: public
  azure:location: WestUS
  prefect-server-azure:k8s-node-type: Standard_B1ms
  prefect-server-azure:k8s-version: 1.18.10
  # prefect-server-azure:service-principal-password: CREATE_PULUMI_SECRET

  # GCP -------------------------------------------------------------

  gcp:project: default
  gcp:zone: us-west1-a
  #prefect-server-gcp:k8s-admin-password: CREATE_PULUMI_SECRET
  prefect-server-gcp:k8s-node-type: n1-standard-1
  prefect-server-gcp:k8s-master-version: ""
  prefect-server-gcp:k8s-node-version: ""


  # Cloud agnostic configuration ---------------------------------------------------------------------------------------

  # If `false`, the default cluster in the local kubeconfig will be used
  # If `true`, a K8s cluster will be created within the given cloud provider
  prefect-server:k8s-create: true
  prefect-server:k8s-node-count: 2
  prefect-server:k8s-admin-username: admin


  # If `false`, the Helm chart will deploy a temporary postgres instance on the K8s cluster unless Helm config values
  # for an existing Postgres instance are passed
  # If `true`, a cloud provider managed Postgres (e.g. CloudSQL) instance will be created
  prefect-server:database-create: true
  prefect-server:database-username: prefect
  #prefect-server:database-password: CREATE_PULUMI_SECRET
  prefect-server:database-storage-mb: 10240
  prefect-server:database-name: prefect

  # If `false`, the Helm chart will not be deployed and you will need to run `helm install` yourself, Helm value
  # overrides with the configuration for connection to the database (if created) will be exported
  # If `true`, the Prefect Server services will be installed on the created (or current) K8s cluster using the Helm
  # chart
  prefect-server:services-create: true
  prefect-server:services-values-override: {}

