config:

  # Cloud provider specific configuration ------------------------------------------------------------------------------

  # Choose a provider to use, one of azure, gcloud, aws
  prefect-server:provider: azure

  # Azure
  azure:environment: public
  azure:location: WestUS

  # A ServicePrincipal must be created to manage the app
  prefect-server-azure:service-principal-password: SECRET


  # Cloud agnostic configuration ---------------------------------------------------------------------------------------

  # If `false`, the default cluster in the local kubeconfig will be used
  # If `true`, a K8s cluster will be created within the given cloud provider
  prefect-server:create-k8s-cluster: false
  prefect-server:k8s-version: 1.18.10

  # If `false`, the Helm chart will deploy a temporary postgres instance on the K8s cluster unless Helm config values
  # for an existing Postgres instance are passed
  # If `true`, a cloud provider managed Postgres (e.g. CloudSQL) instance will be created
  prefect-server:create-managed-postgres: true
